import { UserRole } from './userrole.model';
import { Role } from "./role.model";

export interface User {
  createDate?: string;
  createdBy?: number;
  createdByDescription?: string;
  id?: number;
  updateDate?: string;
  updatedBy?: string;
  updatedByDescription?: string;
  userId: string;
  middleName: string;
  firstName: string;
  lastName: string;
  alias: string;
  userInfo: string;
  employeeId: string;
  phone: string;
  mobile: string;
  fax: string;
  email: string;
  password: string;
  encryptionSalt?: string;
  isActive?: boolean;
  buId: number;
  buName?: string;
  title: string;
  companyName: string;
  managerName: string;
  department: string;
  subDivision: string;
  building: string;
  desk: string;
  status: string;
  address1: string;
  address2: string;
  city: string;
  postalCode: string;
  state: string;
  country: string;
  externalId1?: string;
  externalId2?: string;
  externalId3?: string;
  photoURL?: string;
  secretAnswer1?: string;
  secretAnswer2?: string;
  secretAnswer3?: string;
  secretAnswer4?: string;
  secretAnswer5?: string;
  lastLogin?: string;
  lastFailedLogin?: string;
  latitude?: string;
  longitude?: string;
  ip?: string;
  host?: string;
  port?: number;

  userroles?: UserRole[];
  unassignRoles?: Role[];
}